FROM apache/airflow:2.7.3-python3.10
COPY . /opt/airflow/
USER root
RUN apt-get update && apt-get install -y gcc python3-dev && apt-get install awscli -y
USER airflow
RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt